---
#
# EECS 4287/5287: Principles of Cloud Computing
# Author: Aniruddha Gokhale
# Created: Fall 2017
# Modified: Fall 2020
#
# This playbook is our demo master file
# The goal is to show how to have a single master file which then
# includes multiple plays according to some well-designed choreography
#
# This file is similar to the one in the AnsibleOnly_Local_and_Cloud folder
# For now I just kept one play in here but feel free to add more.
#####################################################
### Play 1: Get facts from all our VMs
#
# Here I show the use of import_tasks from child playbooks
#####################################################
- name: "helper"
  hosts: VM2          # specified in the MyInventory file
  remote_user:  vagrant      # note that the user is ubuntu for 
                             # vagrant-created VM else use the
                             # appropriate user name

  gather_facts: yes          # We ask Ansible to collect all facts
  become_user: no            # No need for sudo as we are not installing anything

  tasks:    # the task to be performed (here I am showing the effect of include_)
   - name: copy kube jobs
     copy:
       src: /vagrant/KubeJobs
       dest: /home/cc/
   # - name: copy server 1
   #   copy:
   #        src: ../server1.properties
   #        dest: /home/cc/

   # - name: copy server 2
   #   copy:
   #        src: ../server2.properties
   #        dest: /home/cc/

   # - name: copy dockerfile
   #   copy:
   #        src: ../dockerfile
   #        dest: /home/cc/

   # - name: copy consumer
   #   copy:
   #        src: ../KubeJobs/consumer.py
   #        dest: /home/cc/

...

