---

 # - name: Start zookeeper
 #   command: bin/zookeeper-server-start.sh config/zookeeper.properties
 #   args:
 #     chdir: /home/cc/kafka_2.13-2.7.0
 #   async: 500
 #   poll: 0
 
 # - name: Pause for 15s
 #   pause:
 #     seconds: 15

 # - name: Start Kafka broker 1
 #   command: bin/kafka-server-start.sh config/server.properties
 #   args:
 #     chdir: /home/cc/kafka_2.13-2.7.0
 #   async: 500
 #   poll: 0

 # - name: Pause for 15s
 #   pause:
 #     seconds: 15
     
 # - name: Start consumer
 #   command: python3 consumer.py > /home/cc/output.txt
 #   args:
 #     chdir: /home/cc/
 #   async: 500
 #   poll: 10
 - name: Start cluster
   command: sudo kubeadm init --node-name kubemaster --pod-network-cidr=10.244.0.0/16

 - name: Execute cluster command 1
   command: mkdir -p $HOME/.kube

 - name: Execute cluster command 2
   command: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config

 - name: Execute cluster command 3
   ansible.builtin.shell: sudo chown $(id -u):$(id -g) $HOME/.kube/config 

 - name: Execute cluster command 4
   command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

 - name: Get join command
   command: kubeadm token create --print-join-command
   register: output



 # - name: Test
 #   debug: var=hostvars['cc@129.114.25.218']['output']['stdout']

 #   register: output

 # - name: Print the output
 #   debug:
 #     msg: "{{ output }}"


...
